### ISSUE TITLE
Recommendations for large list of strings

### ISSUE THREAD

**Issue by mySYSMON** [gvinciguerra/PyGM#1]
Note already asked this in main repo..
I tried to convert my 125 million domains to a unique set of integers but the integer values exceeded the max for 64bit ints. Does anyone know a way to solve this? Maybe something obvious I am not seeing.

**Comment by gvinciguerra** [comment]
Answered in the main repo https://github.com/gvinciguerra/PGM-index/issues/8#issuecomment-743433253 ;)
