### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by sebastian-luna-valero** [gvinciguerra/PyGM#3]
Hi,

Have you considered adding a conda package in https://conda-forge.org/ for `PyGM`?

I can help, and if you are interested, I would like to request your support.

Best regards,
Sebastian

**Comment by gvinciguerra** [comment]
Hi Sebastian, I created a PR at https://github.com/conda-forge/staged-recipes/pull/25909 😉

**Comment by sebastian-luna-valero** [comment]
Great, many thanks!

**Comment by gvinciguerra** [comment]
[Done](https://github.com/conda-forge/pygm-feedstock)!
